--
-- PostgreSQL database dump
--

\restrict Jsmuuta4Of5dEvS4njCahuWWmPkF1IfxM7ArOvaKDHgBsxfdg5t0olPPIg9SGck

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

-- Started on 2025-11-18 23:02:32

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE fase3;
--
-- TOC entry 5070 (class 1262 OID 24576)
-- Name: fase3; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE fase3 WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Portuguese_Brazil.1252';


ALTER DATABASE fase3 OWNER TO postgres;

\unrestrict Jsmuuta4Of5dEvS4njCahuWWmPkF1IfxM7ArOvaKDHgBsxfdg5t0olPPIg9SGck
\connect fase3
\restrict Jsmuuta4Of5dEvS4njCahuWWmPkF1IfxM7ArOvaKDHgBsxfdg5t0olPPIg9SGck

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 224 (class 1259 OID 24664)
-- Name: contem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contem (
    id_estacao smallint NOT NULL,
    id_linha integer NOT NULL
);


ALTER TABLE public.contem OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 24586)
-- Name: estacao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.estacao (
    id_estacao smallint NOT NULL,
    id_gerente smallint,
    id_atendente smallint DEFAULT 0,
    nome character varying(54),
    status character varying(54) DEFAULT 'Ativa'::character varying,
    localizacao character varying(254) NOT NULL
);


ALTER TABLE public.estacao OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 24706)
-- Name: estacao_id_estacao_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.estacao ALTER COLUMN id_estacao ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estacao_id_estacao_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 24577)
-- Name: funcionario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.funcionario (
    id_funcionario smallint NOT NULL,
    nome character varying(254) NOT NULL,
    salario numeric(16,4) NOT NULL,
    funcao character varying(254),
    tipo character varying(51),
    email character varying(254),
    CONSTRAINT funcionario_id CHECK ((id_funcionario > 0)),
    CONSTRAINT "salario positivo" CHECK ((salario > (0)::numeric))
);


ALTER TABLE public.funcionario OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 24633)
-- Name: linha; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.linha (
    id_linha integer NOT NULL,
    id_funcionario smallint,
    extensao character varying(254),
    nome_linha character varying(254),
    tempo_medio smallint DEFAULT 0
);


ALTER TABLE public.linha OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 24707)
-- Name: linha_id_linha_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.linha ALTER COLUMN id_linha ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.linha_id_linha_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 24647)
-- Name: trem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trem (
    id_trem integer NOT NULL,
    id_linha integer NOT NULL,
    id_maquinista smallint NOT NULL,
    capacidade smallint DEFAULT 0,
    status_trem character varying(254)
);


ALTER TABLE public.trem OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 24708)
-- Name: trem_id_trem_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trem ALTER COLUMN id_trem ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trem_id_trem_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 24616)
-- Name: viagem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.viagem (
    id_viagem integer NOT NULL,
    id_trem integer NOT NULL,
    data_partida timestamp with time zone NOT NULL,
    id_maquinista smallint NOT NULL,
    destino character varying(254) NOT NULL,
    data_chegada_prevista timestamp with time zone,
    data_chegada timestamp with time zone,
    status character varying(254),
    qtd_passageiros integer DEFAULT 0
);


ALTER TABLE public.viagem OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 24711)
-- Name: viagem_id_viagem_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.viagem ALTER COLUMN id_viagem ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.viagem_id_viagem_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5060 (class 0 OID 24664)
-- Dependencies: 224
-- Data for Name: contem; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5056 (class 0 OID 24586)
-- Dependencies: 220
-- Data for Name: estacao; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.estacao (id_estacao, id_gerente, id_atendente, nome, status, localizacao) VALUES (1, 57, 34, 'Estrada da Ferreirinha', 'Ativa', 'RJ - Bangu - Rua Tietê');
INSERT INTO public.estacao (id_estacao, id_gerente, id_atendente, nome, status, localizacao) VALUES (9, 12, 22, 'Estação Vassoura', 'Em manuntenção', 'RJ - Realengo - Estrada Manuel Nogueira de Sá');
INSERT INTO public.estacao (id_estacao, id_gerente, id_atendente, nome, status, localizacao) VALUES (10, NULL, NULL, 'Light Breaker', 'Projeto em andamento - Obras', 'RJ - Zona Sul');
INSERT INTO public.estacao (id_estacao, id_gerente, id_atendente, nome, status, localizacao) VALUES (11, NULL, NULL, 'Tree Solve', 'Projeto em andamento - Obras', 'RJ - Zona Norte');
INSERT INTO public.estacao (id_estacao, id_gerente, id_atendente, nome, status, localizacao) VALUES (12, 2, 13, 'Estação Miguel Couto', 'Ativa', 'RJ - Engenho de Dentro - Rua Visconde de Tabuaté');
INSERT INTO public.estacao (id_estacao, id_gerente, id_atendente, nome, status, localizacao) VALUES (13, NULL, 119, 'Estação Sob-Porondé Andares', 'Ativa', 'DC - Vila São Luis - Rua Gomes Sousa');
INSERT INTO public.estacao (id_estacao, id_gerente, id_atendente, nome, status, localizacao) VALUES (14, 203, 45, 'Estação Fidelidade', 'Ativa', 'RJ - Méier - Avenida Amaro Cavalcanti');
INSERT INTO public.estacao (id_estacao, id_gerente, id_atendente, nome, status, localizacao) VALUES (15, NULL, 21, 'Estação do Seu João', 'Ativa', 'CG - Campo Grande - Estrada do Cabuçu');
INSERT INTO public.estacao (id_estacao, id_gerente, id_atendente, nome, status, localizacao) VALUES (16, NULL, NULL, 'Estação das Dores', 'Em manuntenção', 'RJ - Vila Isabel - Boulevard 28 de Setembro');


--
-- TOC entry 5055 (class 0 OID 24577)
-- Dependencies: 219
-- Data for Name: funcionario; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.funcionario (id_funcionario, nome, salario, funcao, tipo, email) VALUES (22, 'Barner Honório Silva', 4396.5000, 'Atendente', 'CLT', 'barner32@gmail.com');
INSERT INTO public.funcionario (id_funcionario, nome, salario, funcao, tipo, email) VALUES (13, 'Antonio Lancelote Brudge', 1354.9000, 'Atendente', 'Estagiario', 'ant.13onio@gmail.com');
INSERT INTO public.funcionario (id_funcionario, nome, salario, funcao, tipo, email) VALUES (45, 'Maria da Silva Rodrigues', 4596.9000, 'Atendente', 'CLT', 'maria56silva@yahoo.com');
INSERT INTO public.funcionario (id_funcionario, nome, salario, funcao, tipo, email) VALUES (136, 'Gabriel Ferro dos Santos', 6250.8700, 'Maquinista', 'PJ', 'amotrens12@yahoo.com');
INSERT INTO public.funcionario (id_funcionario, nome, salario, funcao, tipo, email) VALUES (10, 'Luiza Mares de Sousa', 1354.9000, 'Atendente', 'Estagiario', 'luizaa3sousa@gmail.com');
INSERT INTO public.funcionario (id_funcionario, nome, salario, funcao, tipo, email) VALUES (177, 'Marcos Júnior do Vale', 3766.9800, 'Maquinista', 'PJ', 'junior10vale@hotmail.com');
INSERT INTO public.funcionario (id_funcionario, nome, salario, funcao, tipo, email) VALUES (12, 'Marco Béquer Nonato', 5443.7600, 'Maquinista', 'PJ', 'bequer123n@outlook.com');
INSERT INTO public.funcionario (id_funcionario, nome, salario, funcao, tipo, email) VALUES (2, 'Carlos Henrique Soares', 6789.5500, 'Gerente de Operacoes', 'CLT', 'henrique11.soa@gmail.com');
INSERT INTO public.funcionario (id_funcionario, nome, salario, funcao, tipo, email) VALUES (57, 'Bruna Fagundes de Abulquerque', 6879.1300, 'Gerente de Operacoes', 'CLT', 'brufag12ab@gmail.com');
INSERT INTO public.funcionario (id_funcionario, nome, salario, funcao, tipo, email) VALUES (21, 'Priscilla Ramos de Maria', 4396.5000, 'Atendente', 'CLT', 'priscila3ramos@hotmail.com');
INSERT INTO public.funcionario (id_funcionario, nome, salario, funcao, tipo, email) VALUES (166, 'Theo Jorge de Mesquita', 6133.2800, 'Maquinista', 'PJ', 'teho23m@gmail.com');
INSERT INTO public.funcionario (id_funcionario, nome, salario, funcao, tipo, email) VALUES (88, 'Renato Alves Monteiro', 5120.4000, 'Maquinista', 'PJ', 'renato.monteiro88@gmail.com');
INSERT INTO public.funcionario (id_funcionario, nome, salario, funcao, tipo, email) VALUES (34, 'Juliana Moura Pacheco', 3980.7500, 'Atendente', 'CLT', 'julipacheco34@yahoo.com');
INSERT INTO public.funcionario (id_funcionario, nome, salario, funcao, tipo, email) VALUES (119, 'Felipe Gomes Arruda', 1420.3000, 'Atendente', 'Estagiario', 'felipe.arruda119@hotmail.com');
INSERT INTO public.funcionario (id_funcionario, nome, salario, funcao, tipo, email) VALUES (203, 'Sabrina Castro Nogueira', 7245.9000, 'Gerente de Operacoes', 'PJ', 'sabrina.nogueira203@gmail.com');
INSERT INTO public.funcionario (id_funcionario, nome, salario, funcao, tipo, email) VALUES (91, 'Otávio Fernandes Dias', 3899.6000, 'Maquinista', 'PJ', 'otaviofd91@outlook.com');


--
-- TOC entry 5058 (class 0 OID 24633)
-- Dependencies: 222
-- Data for Name: linha; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5059 (class 0 OID 24647)
-- Dependencies: 223
-- Data for Name: trem; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5057 (class 0 OID 24616)
-- Dependencies: 221
-- Data for Name: viagem; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5071 (class 0 OID 0)
-- Dependencies: 225
-- Name: estacao_id_estacao_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.estacao_id_estacao_seq', 1, false);


--
-- TOC entry 5072 (class 0 OID 0)
-- Dependencies: 226
-- Name: linha_id_linha_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.linha_id_linha_seq', 1, false);


--
-- TOC entry 5073 (class 0 OID 0)
-- Dependencies: 227
-- Name: trem_id_trem_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trem_id_trem_seq', 1, false);


--
-- TOC entry 5074 (class 0 OID 0)
-- Dependencies: 228
-- Name: viagem_id_viagem_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.viagem_id_viagem_seq', 1, false);


--
-- TOC entry 4899 (class 2606 OID 24670)
-- Name: contem contem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contem
    ADD CONSTRAINT contem_pkey PRIMARY KEY (id_estacao, id_linha);


--
-- TOC entry 4889 (class 2606 OID 24596)
-- Name: estacao estacao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estacao
    ADD CONSTRAINT estacao_pkey PRIMARY KEY (id_estacao);


--
-- TOC entry 4887 (class 2606 OID 24585)
-- Name: funcionario funcionario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funcionario
    ADD CONSTRAINT funcionario_pkey PRIMARY KEY (id_funcionario);


--
-- TOC entry 4895 (class 2606 OID 24641)
-- Name: linha linha_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.linha
    ADD CONSTRAINT linha_pkey PRIMARY KEY (id_linha);


--
-- TOC entry 4897 (class 2606 OID 24653)
-- Name: trem trem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trem
    ADD CONSTRAINT trem_pkey PRIMARY KEY (id_trem);


--
-- TOC entry 4891 (class 2606 OID 24682)
-- Name: viagem uk_viagem_id_trem_data_partida; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.viagem
    ADD CONSTRAINT uk_viagem_id_trem_data_partida UNIQUE (id_trem, data_partida);


--
-- TOC entry 4893 (class 2606 OID 24625)
-- Name: viagem viagem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.viagem
    ADD CONSTRAINT viagem_pkey PRIMARY KEY (id_viagem);


--
-- TOC entry 4900 (class 2606 OID 24602)
-- Name: estacao estacao_id_atendente_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estacao
    ADD CONSTRAINT estacao_id_atendente_fkey FOREIGN KEY (id_atendente) REFERENCES public.funcionario(id_funcionario);


--
-- TOC entry 4901 (class 2606 OID 24597)
-- Name: estacao estacao_id_gerente_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estacao
    ADD CONSTRAINT estacao_id_gerente_fkey FOREIGN KEY (id_gerente) REFERENCES public.funcionario(id_funcionario);


--
-- TOC entry 4906 (class 2606 OID 24671)
-- Name: contem fk_contem_estacao; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contem
    ADD CONSTRAINT fk_contem_estacao FOREIGN KEY (id_estacao) REFERENCES public.estacao(id_estacao);


--
-- TOC entry 4907 (class 2606 OID 24676)
-- Name: contem fk_contem_linha; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contem
    ADD CONSTRAINT fk_contem_linha FOREIGN KEY (id_linha) REFERENCES public.linha(id_linha);


--
-- TOC entry 4903 (class 2606 OID 24642)
-- Name: linha fk_funcionario_linha; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.linha
    ADD CONSTRAINT fk_funcionario_linha FOREIGN KEY (id_funcionario) REFERENCES public.funcionario(id_funcionario);


--
-- TOC entry 4904 (class 2606 OID 24659)
-- Name: trem fk_trem_funcionario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trem
    ADD CONSTRAINT fk_trem_funcionario FOREIGN KEY (id_maquinista) REFERENCES public.funcionario(id_funcionario);


--
-- TOC entry 4905 (class 2606 OID 24654)
-- Name: trem fk_trem_linha; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trem
    ADD CONSTRAINT fk_trem_linha FOREIGN KEY (id_linha) REFERENCES public.linha(id_linha);


--
-- TOC entry 4902 (class 2606 OID 24628)
-- Name: viagem viagem_id_funcionario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.viagem
    ADD CONSTRAINT viagem_id_funcionario_fkey FOREIGN KEY (id_maquinista) REFERENCES public.funcionario(id_funcionario);


-- Completed on 2025-11-18 23:02:32

--
-- PostgreSQL database dump complete
--

\unrestrict Jsmuuta4Of5dEvS4njCahuWWmPkF1IfxM7ArOvaKDHgBsxfdg5t0olPPIg9SGck

